### ISSUE TITLE
All function designs in error are added to fd_error_log

### ISSUE THREAD

**Issue by Rezenders** [meta-control/mc_mros_reasoner#141]
Every time a function grounding violates a NFR the objective it is solving is added to the function design `fd_error_log`. 
This shouldn't be the case for all violations, in the smart home for example we don't add the FDs to an error log. In addition, it doesn't make sense to block an FD for a violating a non-functional requirement. 

Another issue I see is that the relationship order seems to be inverted. I would say that an FD is added to the objective error log and not the opposite. 

But anyway, regarding the main issue I suggest:

- Making a distinction between non-functional requirements and functional requirements
- Only when a functional requirement is violated, the function design should be blocked

A quick solution for this in MROS could be to
- [x] #143
- [x] #144
- [ ] Add `IN_ERROR_FR` to `o_status`

**Comment by Rezenders** [comment]
Done

**Comment by Rezenders** [comment]
@chcorbato FYI

**Comment by chcorbato** [comment]
We need to keep track of this change in the `tomasys` metamodel, i.e. values for 'Objective.status'
Have you edited tomasys.owl in some branch @Rezenders ?
Maybe good to indicate it here.

**Comment by Rezenders** [comment]
I only modified mros.owl and its SWRL rules. Changes are in the main branch.
I didn't change the o_status, but it is working. I will add that to tomasys.

**Comment by Rezenders** [comment]
Done at https://github.com/meta-control/mc_mdl_tomasys/commit/a020191e7e7c52d4f5aa3e2240fca2ea269bf940
