### ISSUE TITLE
Domain-specific knowledge is currently encoded in the generic parsing to tomasys, including domain knowledge rules

### ISSUE THREAD

**Issue by chcorbato** [meta-control/mc_mros_reasoner#169]
See the parsing of water visibility and associated rule from the SUAVE exemplar

https://github.com/meta-control/mc_mros_reasoner/blob/deeeb43ce0a1bbf805283e27a878627fbb7394f7/mros2_reasoner/mros2_reasoner/tomasys.py#L257-L266

https://github.com/meta-control/mc_mros_reasoner/blob/deeeb43ce0a1bbf805283e27a878627fbb7394f7/mros2_reasoner/mros2_reasoner/tomasys.py#L298-L314

**Comment by Rezenders** [comment]
Solved at: 4b9caa2f802c5788601fb8146f24a7adc047e93c

Using `qa_comparison_operator`: https://github.com/meta-control/mc_mdl_tomasys/issues/9

**Comment by Rezenders** [comment]
I think we should add a `hasNFR` property for the FDs and use it instead of the `hasQAEstimation` property
