### ISSUE TITLE
Update the README of this repo to indicate how to parse the OWL file

### ISSUE THREAD

**Issue by marioney** [meta-control/mc_mros_reasoner#30]
Ontology file should be given as arg to the `run.launch` file

e.g.

`roslaunch mros1_reasoner run.launch onto:=mvp.owl`

**Comment by gavanderhoorn** [comment]
It's off-topic, but `onto` sounds like a rather strange name for this arg.

Should it be `about` instead? You reason *about* something. Not onto.

**Comment by chcorbato** [comment]
> It's off-topic, but `onto` sounds like a rather strange name for this arg.
> 
> Should it be `about` instead? You reason _about_ something. Not onto.

Agree `onto` sounds weird. I propose to change it to `ontology`
