### ISSUE TITLE
Missing to reconfigure despite Observed qa_energy above threshold for some messages

### ISSUE THREAD

**Issue by chcorbato** [meta-control/mc_mros_reasoner#51]
This is related to the current architecture of the `mros_reasoner` (see discussions [1](url) and [2](https://github.com/rosin-project/mros1_reasoner/issues/48#issuecomment-633042731)), that is:
- async reception of input data
- sync execution of the reasoning with that data (only most recent value)

I propose to keep the highest value received on each `timer_cb` cycle for reasoning

@marioney @gavanderhoorn what do you think? We need a quick fix now for these experiments to provide useful results for the paper, but also a proper solution maybe later, rethinking the execution model of the metacontroller.

**Comment by chcorbato** [comment]
related to https://github.com/rosin-project/mros1_reasoner/issues/48#issuecomment-633042731
I change to wontfix the issue thanks to Mario's fix with a lock 8cba195 see https://github.com/rosin-project/mros1_reasoner/issues/48#issuecomment-633102711

**Comment by Rezenders** [comment]
This issue has been labeled with wontfix, I am closing it.
